/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hastatakipsist;

import Helper.db;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Aleyna
 */
public class doktor_tahlil_gorme extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int columnsNumber = 0;

    /**
     * Creates new form doktor_tahlil_gorme
     */
    public doktor_tahlil_gorme() {
        initComponents();
        retrievetableIdrar2();
        retrievetableKAN2();
        
        setSize(1500,700);
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        hasta_tc1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_renk = new javax.swing.JTextField();
        txt_tarih1 = new javax.swing.JTextField();
        txt_glukoz = new javax.swing.JTextField();
        txt_protein = new javax.swing.JTextField();
        txt_ph = new javax.swing.JTextField();
        txt_dansite = new javax.swing.JTextField();
        txt_bilirubin = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_keton = new javax.swing.JTextField();
        txt_nitrit = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_urobili = new javax.swing.JTextField();
        txt_gorunum = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        tc_arama2 = new javax.swing.JTextField();
        btn_tcbul8 = new javax.swing.JButton();
        btn_idrar_reset = new javax.swing.JButton();
        tbl_idrar1 = new javax.swing.JScrollPane();
        tbl_idrar = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hasta_tc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_demir = new javax.swing.JTextField();
        txt_tarih = new javax.swing.JTextField();
        txt_lym = new javax.swing.JTextField();
        txt_gray = new javax.swing.JTextField();
        txt_gran = new javax.swing.JTextField();
        txt_wbc = new javax.swing.JTextField();
        txt_lymy = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_rbc = new javax.swing.JTextField();
        txt_hgb = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_mıd = new javax.swing.JTextField();
        txt_crp = new javax.swing.JTextField();
        txt_hct = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_plt = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        tc_arama = new javax.swing.JTextField();
        btn_tcbul7 = new javax.swing.JButton();
        btn_kan_reset = new javax.swing.JButton();
        tbl_kan1 = new javax.swing.JScrollPane();
        tbl_kan = new javax.swing.JTable();
        btn_onceki_sayfa = new javax.swing.JButton();
        btn_oturumukapat = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setOpaque(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("pH:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Tarih:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Protein:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("TC:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Dansite:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Renk:");

        hasta_tc1.setToolTipText("");
        hasta_tc1.setEnabled(false);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Görünüm:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Glukoz:");

        txt_renk.setToolTipText("");
        txt_renk.setEnabled(false);

        txt_tarih1.setToolTipText("");
        txt_tarih1.setEnabled(false);

        txt_glukoz.setToolTipText("");
        txt_glukoz.setEnabled(false);

        txt_protein.setToolTipText("");
        txt_protein.setEnabled(false);

        txt_ph.setToolTipText("");
        txt_ph.setEnabled(false);

        txt_dansite.setToolTipText("");
        txt_dansite.setEnabled(false);

        txt_bilirubin.setToolTipText("");
        txt_bilirubin.setEnabled(false);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Ürobilinojen:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Nitrit:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("Bilirubin:");

        txt_keton.setToolTipText("");
        txt_keton.setEnabled(false);

        txt_nitrit.setToolTipText("");
        txt_nitrit.setEnabled(false);

        jLabel27.setText("Keton:");

        txt_urobili.setToolTipText("");
        txt_urobili.setEnabled(false);

        txt_gorunum.setToolTipText("");
        txt_gorunum.setEnabled(false);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hasta_tc1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_ph, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(txt_keton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel9)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_tarih1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(txt_protein)
                    .addComponent(txt_nitrit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_renk, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(txt_glukoz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_gorunum, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(txt_bilirubin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_dansite, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_urobili, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel14Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_glukoz, txt_nitrit, txt_protein, txt_renk, txt_tarih1});

        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasta_tc1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_tarih1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(txt_renk, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txt_dansite, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gorunum, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ph, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txt_protein, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_glukoz, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(txt_bilirubin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel24)
                    .addComponent(txt_urobili, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_keton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(txt_nitrit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(479, 479, 479))
        );

        jPanel14Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_glukoz, txt_nitrit, txt_protein, txt_renk, txt_tarih1});

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel36.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel36.setText("TC :");

        btn_tcbul8.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_tcbul8.setText("BUL");
        btn_tcbul8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tcbul8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tc_arama2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_tcbul8, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(btn_tcbul8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tc_arama2))
                .addContainerGap())
        );

        btn_idrar_reset.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_idrar_reset.setText("RESETLE");
        btn_idrar_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_idrar_resetActionPerformed(evt);
            }
        });

        tbl_idrar1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tbl_idrar1.setEnabled(false);

        tbl_idrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "TC", "Tarih", "Renk", "Görünüm", "Dansite", "pH", "Protein", "Glukoz", "Bilirubin", "Ürobilinojen", "Keton", "Nitrit"
            }
        ));
        tbl_idrar.setAutoscrolls(false);
        tbl_idrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_idrar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tbl_idrar.setIntercellSpacing(new java.awt.Dimension(1, 4));
        tbl_idrar.setOpaque(false);
        tbl_idrar.setRequestFocusEnabled(false);
        tbl_idrar.getTableHeader().setReorderingAllowed(false);
        tbl_idrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_idrarMouseClicked(evt);
            }
        });
        tbl_idrar1.setViewportView(tbl_idrar);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_idrar_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(tbl_idrar1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_idrar_reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbl_idrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("İDRAR TAHLİLLERİ", jPanel2);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("GRAN:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Tarih:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("GRA%:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("TC:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("WBC:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Demir:");

        hasta_tc.setToolTipText("");
        hasta_tc.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("CRP:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("LYM:");

        txt_demir.setToolTipText("");
        txt_demir.setEnabled(false);

        txt_tarih.setToolTipText("");
        txt_tarih.setEnabled(false);

        txt_lym.setToolTipText("");
        txt_lym.setEnabled(false);

        txt_gray.setToolTipText("");
        txt_gray.setEnabled(false);

        txt_gran.setToolTipText("");
        txt_gran.setEnabled(false);

        txt_wbc.setToolTipText("");
        txt_wbc.setEnabled(false);

        txt_lymy.setToolTipText("");
        txt_lymy.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("MID:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("HGB:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("LYM%:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("HCT:");

        txt_rbc.setToolTipText("");
        txt_rbc.setEnabled(false);

        txt_hgb.setToolTipText("");
        txt_hgb.setEnabled(false);

        jLabel1.setText("RBC:");

        txt_mıd.setToolTipText("");
        txt_mıd.setEnabled(false);

        txt_crp.setToolTipText("");
        txt_crp.setEnabled(false);

        txt_hct.setToolTipText("");
        txt_hct.setEnabled(false);

        jLabel2.setText("PLT:");

        txt_plt.setToolTipText("");
        txt_plt.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hasta_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_gran, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_rbc, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel5)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_gray, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txt_hgb, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(txt_demir, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txt_lym, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txt_hct, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_lymy, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_crp, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_wbc, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_mıd, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txt_plt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasta_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txt_demir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_wbc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_crp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_gran, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txt_gray, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_lym, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txt_lymy, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel13)
                    .addComponent(txt_mıd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_rbc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txt_hgb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel1)
                    .addComponent(txt_hct, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txt_plt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(461, 461, 461))
        );

        jLabel35.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel35.setText("TC :");

        btn_tcbul7.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_tcbul7.setText("BUL");
        btn_tcbul7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tcbul7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tc_arama, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_tcbul7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tc_arama)
                    .addComponent(btn_tcbul7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btn_kan_reset.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_kan_reset.setText("RESETLE");
        btn_kan_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kan_resetActionPerformed(evt);
            }
        });

        tbl_kan1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tbl_kan1.setEnabled(false);

        tbl_kan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "TC", "Tarih", "Demir", "CRP", "WBC", "GRAN", "GRA%", "LYM", "LYM %", "MID", "RBC", "HGB", "HCT", "PLT"
            }
        ));
        tbl_kan.setAutoscrolls(false);
        tbl_kan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_kan.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tbl_kan.setIntercellSpacing(new java.awt.Dimension(1, 4));
        tbl_kan.setOpaque(false);
        tbl_kan.setRequestFocusEnabled(false);
        tbl_kan.getTableHeader().setReorderingAllowed(false);
        tbl_kan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kan_clicked(evt);
            }
        });
        tbl_kan1.setViewportView(tbl_kan);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_kan_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addComponent(tbl_kan1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_kan_reset)
                        .addGap(19, 19, 19)))
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbl_kan1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("KAN TAHLİLLERİ", jPanel3);

        btn_onceki_sayfa.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_onceki_sayfa.setText("Önceki sayfa");
        btn_onceki_sayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_onceki_sayfaActionPerformed(evt);
            }
        });

        btn_oturumukapat.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_oturumukapat.setText("OTURUMU KAPAT");
        btn_oturumukapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oturumukapatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_onceki_sayfa, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(717, 717, 717)
                        .addComponent(btn_oturumukapat))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1053, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_oturumukapat, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_onceki_sayfa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(210, 20, 1077, 650);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ıcon/Medical+Banner.jpg"))); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(0, 0, 1500, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void TC_kontrol() {
        String kimlikNo = btn_tcbul7.getText();
        if (kimlikNo.length() != 11) {
            JOptionPane.showMessageDialog(null, "Lütfen 11 haneli numara giriniz.", "TC Kimlik No Sorgulama", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void TC_kontrol1() {
        String kimlikNo = btn_tcbul8.getText();
        if (kimlikNo.length() != 11) {
            JOptionPane.showMessageDialog(null, "Lütfen 11 haneli numara giriniz.", "TC Kimlik No Sorgulama", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void retrievetableIdrar(String TC) {
        try {
            DefaultTableModel tbl = (DefaultTableModel) tbl_idrar.getModel();
            while (tbl.getRowCount() > 0) {
                tbl.removeRow(0);
            }

            conn = db.connection_db();
            String sql = "SELECT * FROM IdrarTahlil WHERE TC='" + TC + "'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            columnsNumber = rsmd.getColumnCount();

            String[] data = new String[columnsNumber];
            while (rs.next()) {
                for (int i = 0; i < data.length; i++) {
                    data[i] = rs.getString(i + 1);
                }

                DefaultTableModel tblModel = (DefaultTableModel) tbl_idrar.getModel();
                tblModel.addRow(data);
            }
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, ex);

        } finally {
            try {
                conn.close();
            } catch (Exception ex) {

                JOptionPane.showMessageDialog(null, ex);

            }
        }

    }

    private void retrievetableKAN(String TC) {
        try {

            DefaultTableModel tbl = (DefaultTableModel) tbl_kan.getModel();
            while (tbl.getRowCount() > 0) {
                tbl.removeRow(0);
            }

            conn = db.connection_db();
            String sql = "SELECT * FROM KanTahlil WHERE TC='" + TC + "'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            columnsNumber = rsmd.getColumnCount();

            String[] data = new String[columnsNumber];
            while (rs.next()) {
                for (int i = 0; i < data.length; i++) {
                    data[i] = rs.getString(i + 1);
                }

                DefaultTableModel tblModel = (DefaultTableModel) tbl_kan.getModel();
                tblModel.addRow(data);
            }
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, ex);

        } finally {
            try {
                conn.close();
            } catch (Exception ex) {

                JOptionPane.showMessageDialog(null, ex);

            }
        }

    }

    private void retrievetableIdrar2() {
        try {
            DefaultTableModel tbl = (DefaultTableModel) tbl_idrar.getModel();
            while (tbl.getRowCount() > 0) {
                tbl.removeRow(0);
            }

            conn = Helper.db.connection_db();
            String sql = "SELECT * FROM IdrarTahlil";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            columnsNumber = rsmd.getColumnCount();

            String[] data = new String[columnsNumber];
            while (rs.next()) {
                for (int i = 0; i < data.length; i++) {
                    data[i] = rs.getString(i + 1);
                }

                DefaultTableModel tblModel = (DefaultTableModel) tbl_idrar.getModel();
                tblModel.addRow(data);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        } finally {
            try {
                conn.close();
            } catch (Exception ex) {

            }
        }

    }

    private void retrievetableKAN2() {
        try {
            DefaultTableModel table = (DefaultTableModel) tbl_kan.getModel();
            while (table.getRowCount() > 0) {
                table.removeRow(0);
            }
            conn = db.connection_db();
            String sql = "select * from KanTahlil";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            columnsNumber = rsmd.getColumnCount();

            String[] data = new String[columnsNumber];
            while (rs.next()) {
                for (int i = 0; i < data.length; i++) {
                    data[i] = rs.getString(i + 1);
                }

                DefaultTableModel tableModel = (DefaultTableModel) tbl_kan.getModel();
                tableModel.addRow(data);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                conn.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }

    private void btn_onceki_sayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_onceki_sayfaActionPerformed
        this.dispose();
        doktor_islem_secim d = new doktor_islem_secim();
        d.setVisible(true);
    }//GEN-LAST:event_btn_onceki_sayfaActionPerformed

    private void btn_oturumukapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oturumukapatActionPerformed
        this.dispose();
        login l = new login();
        l.setVisible(true);

    }//GEN-LAST:event_btn_oturumukapatActionPerformed

    private void btn_tcbul7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tcbul7ActionPerformed
        String HastaTC = "";
        String data = "";
        try {
            conn = db.connection_db();
            String sql = "SELECT * FROM KanTahlil WHERE TC=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, tc_arama.getText());
            rs = pst.executeQuery();

            if (rs.next()) {
                HastaTC = rs.getString("TC");
                JOptionPane.showMessageDialog(null, "TC BULUNDU");

            } else {
                JOptionPane.showMessageDialog(null, "TC BULUNAMADI ! ");
            }
        } catch (Exception ex) {

        }
        try {
            conn.close();
            retrievetableKAN(HastaTC);
        } catch (Exception ex) {

        }

        try {
            conn = db.connection_db();
            String sql = "SELECT * FROM KanTahlil WHERE TC=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, tc_arama.getText());
            rs = pst.executeQuery();
            while (rs.next()) {
                data = rs.getString("TC");
                hasta_tc.setText(data);
                data = rs.getString("Tarih");
                txt_tarih.setText(data);
                data = rs.getString("Demir");
                txt_demir.setText(data);
                data = rs.getString("CRP");
                txt_crp.setText(data);
                data = rs.getString("WBC");
                txt_wbc.setText(data);
                data = rs.getString("GRAN");
                txt_gran.setText(data);
                data = rs.getString("GRAy");
                txt_gray.setText(data);
                data = rs.getString("LYM");
                txt_lym.setText(data);
                data = rs.getString("LYMy");
                txt_lymy.setText(data);
                data = rs.getString("MID");
                txt_mıd.setText(data);
                data = rs.getString("RBC");
                txt_rbc.setText(data);
                data = rs.getString("HGB");
                txt_hgb.setText(data);
                data = rs.getString("HCT");
                txt_hct.setText(data);
                data = rs.getString("PLT");
                txt_plt.setText(data);

            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_btn_tcbul7ActionPerformed

    private void btn_tcbul8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tcbul8ActionPerformed
        String HastaTC = "";
        String data = "";
        try {
            conn = Helper.db.connection_db();
            String sql = "SELECT * FROM IdrarTahlil WHERE TC=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, tc_arama2.getText());
         
            rs = pst.executeQuery();

            if (rs.next()) {
                HastaTC = rs.getString("TC");
                JOptionPane.showMessageDialog(null, "TC BULUNDU.");

            } else {
                JOptionPane.showMessageDialog(null, "TC BULUNAMADI !");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        try {
            conn.close();
            retrievetableIdrar(HastaTC);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        try {
            conn = Helper.db.connection_db();
            String sql = "SELECT * FROM IdrarTahlil WHERE TC=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, tc_arama2.getText());
            rs = pst.executeQuery();
            while (rs.next()) {
                data = rs.getString("TC");
                hasta_tc1.setText(data);
                data = rs.getString("Tarih");
                txt_tarih1.setText(data);
                data = rs.getString("Renk");
                txt_renk.setText(data);
                data = rs.getString("Görünüm");
                txt_gorunum.setText(data);
                data = rs.getString("Dansite");
                txt_dansite.setText(data);
                data = rs.getString("pH");
                txt_ph.setText(data);
                data = rs.getString("Protein");
                txt_protein.setText(data);
                data = rs.getString("Glukoz");
                txt_glukoz.setText(data);
                data = rs.getString("Bilirubin");
                txt_bilirubin.setText(data);
                data = rs.getString("Ürobilinojen");
                txt_urobili.setText(data);
                data = rs.getString("Keton");
                txt_keton.setText(data);
                data = rs.getString("Nitrit");
                txt_nitrit.setText(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_tcbul8ActionPerformed

    public void resetleidrar() {
        tc_arama2.setText("");
        hasta_tc1.setText("");
        txt_tarih1.setText("");
        txt_gorunum.setText("");
        txt_renk.setText("");
        txt_dansite.setText("");
        txt_ph.setText("");
        txt_protein.setText("");
        txt_glukoz.setText("");
        txt_bilirubin.setText("");
        txt_urobili.setText("");
        txt_keton.setText("");
        txt_nitrit.setText("");
    }

    private void btn_idrar_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_idrar_resetActionPerformed

        resetleidrar();
        retrievetableIdrar2();

    }//GEN-LAST:event_btn_idrar_resetActionPerformed
    private void resetlekan() {
        tc_arama.setText("");
        hasta_tc.setText("");
        txt_tarih.setText("");
        txt_demir.setText("");
        txt_wbc.setText("");
        txt_gran.setText("");
        txt_crp.setText("");
        txt_gray.setText("");
        txt_lym.setText("");
        txt_lymy.setText("");
        txt_mıd.setText("");
        txt_rbc.setText("");
        txt_hgb.setText("");
        txt_hct.setText("");
        txt_plt.setText("");
    }
    private void btn_kan_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kan_resetActionPerformed

        resetlekan();
        retrievetableKAN2();
    }//GEN-LAST:event_btn_kan_resetActionPerformed

    private void kan_clicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kan_clicked
    int i = tbl_kan.getSelectedRow();
        TableModel model = tbl_kan.getModel();
        hasta_tc.setText(model.getValueAt(i, 0).toString());
        txt_tarih.setText(model.getValueAt(i, 1).toString());
        txt_demir.setText(model.getValueAt(i, 2).toString());
        txt_crp.setText(model.getValueAt(i, 3).toString());
        txt_wbc.setText(model.getValueAt(i, 4).toString());
        txt_gran.setText(model.getValueAt(i, 5).toString());
        txt_gray.setText(model.getValueAt(i, 6).toString());
        txt_lym.setText(model.getValueAt(i, 7).toString());
        txt_lymy.setText(model.getValueAt(i, 8).toString());
        txt_mıd.setText(model.getValueAt(i, 9).toString());
        txt_rbc.setText(model.getValueAt(i, 10).toString());
        txt_hgb.setText(model.getValueAt(i, 11).toString());
        txt_hct.setText(model.getValueAt(i, 12).toString());
        txt_plt.setText(model.getValueAt(i, 13).toString());
    }//GEN-LAST:event_kan_clicked

    private void tbl_idrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_idrarMouseClicked
    int i = tbl_idrar.getSelectedRow();
        TableModel model = tbl_idrar.getModel();
        hasta_tc1.setText(model.getValueAt(i, 0).toString());
        txt_tarih1.setText(model.getValueAt(i, 1).toString());
        txt_renk.setText(model.getValueAt(i, 2).toString());
        txt_gorunum.setText(model.getValueAt(i, 3).toString());
        txt_dansite.setText(model.getValueAt(i, 4).toString());
        txt_ph.setText(model.getValueAt(i, 5).toString());
        txt_protein.setText(model.getValueAt(i, 6).toString());
        txt_glukoz.setText(model.getValueAt(i, 7).toString());
        txt_bilirubin.setText(model.getValueAt(i, 8).toString());
        txt_urobili.setText(model.getValueAt(i, 9).toString());
        txt_keton.setText(model.getValueAt(i, 10).toString());
        txt_nitrit.setText(model.getValueAt(i, 11).toString());
    }//GEN-LAST:event_tbl_idrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doktor_tahlil_gorme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doktor_tahlil_gorme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doktor_tahlil_gorme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doktor_tahlil_gorme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doktor_tahlil_gorme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_idrar_reset;
    private javax.swing.JButton btn_kan_reset;
    private javax.swing.JButton btn_onceki_sayfa;
    private javax.swing.JButton btn_oturumukapat;
    private javax.swing.JButton btn_tcbul7;
    private javax.swing.JButton btn_tcbul8;
    private javax.swing.JTextField hasta_tc;
    private javax.swing.JTextField hasta_tc1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbl_idrar;
    private javax.swing.JScrollPane tbl_idrar1;
    private javax.swing.JTable tbl_kan;
    private javax.swing.JScrollPane tbl_kan1;
    private javax.swing.JTextField tc_arama;
    private javax.swing.JTextField tc_arama2;
    private javax.swing.JTextField txt_bilirubin;
    private javax.swing.JTextField txt_crp;
    private javax.swing.JTextField txt_dansite;
    private javax.swing.JTextField txt_demir;
    private javax.swing.JTextField txt_glukoz;
    private javax.swing.JTextField txt_gorunum;
    private javax.swing.JTextField txt_gran;
    private javax.swing.JTextField txt_gray;
    private javax.swing.JTextField txt_hct;
    private javax.swing.JTextField txt_hgb;
    private javax.swing.JTextField txt_keton;
    private javax.swing.JTextField txt_lym;
    private javax.swing.JTextField txt_lymy;
    private javax.swing.JTextField txt_mıd;
    private javax.swing.JTextField txt_nitrit;
    private javax.swing.JTextField txt_ph;
    private javax.swing.JTextField txt_plt;
    private javax.swing.JTextField txt_protein;
    private javax.swing.JTextField txt_rbc;
    private javax.swing.JTextField txt_renk;
    private javax.swing.JTextField txt_tarih;
    private javax.swing.JTextField txt_tarih1;
    private javax.swing.JTextField txt_urobili;
    private javax.swing.JTextField txt_wbc;
    // End of variables declaration//GEN-END:variables
}
