/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hastatakipsist;

import Helper.*;
import java.awt.*;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.OutputStream;
import java.io.PrintStream;
import java.sql.*;
import java.time.LocalDate;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Aleyna
 */
public class doktor_islem extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int columnsNumber = 0;

    /**
     * Creates new form doktor_islem
     */
    public doktor_islem() {
        initComponents();
        retrievetableMUAYENE();
        
        setSize(1500,700);
        
        try {
            conn = db.connection_db();
            String sql = "SELECT * FROM KANGRUBU";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                cmb_kangrubu.addItem(rs.getString("KanGrubu"));
            }
        } catch (Exception ex) {

        } finally {
            try {
                conn.close();
            } catch (Exception ex) {

            }
        }
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }


    private void retrievetable(String TC) {
        try {
            DefaultTableModel tbl = (DefaultTableModel) muayene_kayit.getModel();
            while (tbl.getRowCount() > 0) {
                tbl.removeRow(0);
            }

            conn = Helper.db.connection_db();
            String sql = "SELECT * FROM MUAYENE WHERE TC='" + TC + "'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            columnsNumber = rsmd.getColumnCount();

            String[] data = new String[columnsNumber];
            while (rs.next()) {
                for (int i = 0; i < data.length; i++) {
                    data[i] = rs.getString(i + 1);
                }

                DefaultTableModel tblModel = (DefaultTableModel) muayene_kayit.getModel();
                tblModel.addRow(data);
            }
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, ex);

        } finally {
            try {
                conn.close();
            } catch (Exception ex) {

                JOptionPane.showMessageDialog(null, ex);

            }
        }

    }

    private void retrievetableMUAYENE() {
        try {
            DefaultTableModel table = (DefaultTableModel) muayene_kayit.getModel();
            while (table.getRowCount() > 0) {
                table.removeRow(0);
            }
            conn = db.connection_db();
            String sql = "SELECT * FROM MUAYENE";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            columnsNumber = rsmd.getColumnCount();

            String[] data = new String[columnsNumber];
            while (rs.next()) {
                for (int i = 0; i < data.length; i++) {
                    data[i] = rs.getString(i + 1);
                }

                DefaultTableModel tableModel = (DefaultTableModel) muayene_kayit.getModel();
                tableModel.addRow(data);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                conn.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_oncekisayfa = new javax.swing.JButton();
        btn_onceki_sayfa2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        hasta_adsoyad = new javax.swing.JTextField();
        hasta_dogumt = new javax.swing.JTextField();
        hasta_tc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        hasta_ilac = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        hasta_giristarihi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        hasta_cıkıstarihi = new javax.swing.JTextField();
        btn_kayit = new javax.swing.JButton();
        btn_sil = new javax.swing.JButton();
        btn_guncelle = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        hasta_muayene = new javax.swing.JTextField();
        btn_resetle = new javax.swing.JButton();
        hasta_semptom = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btn_yazdir = new javax.swing.JButton();
        btn_kayit1 = new javax.swing.JButton();
        cmb_kangrubu = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        muayene_kayit = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        tc_arama = new javax.swing.JTextField();
        btn_tcbul = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setOpaque(false);

        btn_oncekisayfa.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_oncekisayfa.setText("Önceki sayfa");
        btn_oncekisayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oncekisayfaActionPerformed(evt);
            }
        });

        btn_onceki_sayfa2.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_onceki_sayfa2.setText("OTURUMU KAPAT");
        btn_onceki_sayfa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_onceki_sayfa2ActionPerformed(evt);
            }
        });

        jPanel2.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("TC:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("AD SOYAD:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("DOĞUM TARİHİ:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("KAN GRUBU:");

        jLabel20.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel20.setText("HASTA MUAYENE KAYIT İŞLEMİ ");

        hasta_adsoyad.setToolTipText("");

        hasta_dogumt.setText("GG.AA.YYYY");
        hasta_dogumt.setToolTipText("");

        hasta_tc.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("İLAÇ:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("GİRİŞ TARİHİ:");

        hasta_giristarihi.setText("GG.AA.YYYY");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("ÇIKIŞ TARİHİ:");

        hasta_cıkıstarihi.setText("GG.AA.YYYY");

        btn_kayit.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_kayit.setText("KAYIT ");
        btn_kayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayitActionPerformed(evt);
            }
        });

        btn_sil.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_sil.setText("SİL");
        btn_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silActionPerformed(evt);
            }
        });

        btn_guncelle.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_guncelle.setText("GÜNCELLE");
        btn_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guncelleActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("MUAYENE:");

        hasta_muayene.setToolTipText("");

        btn_resetle.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_resetle.setText("RESETLE");
        btn_resetle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetleActionPerformed(evt);
            }
        });

        hasta_semptom.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("SEMPTOM:");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        btn_yazdir.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_yazdir.setText("YAZDIR");
        btn_yazdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_yazdirActionPerformed(evt);
            }
        });

        btn_kayit1.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_kayit1.setText("REÇETE");
        btn_kayit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayit1ActionPerformed(evt);
            }
        });

        cmb_kangrubu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEÇİNİZ" }));

        muayene_kayit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "TC", "AD SOYAD", "DOĞUM TARİHİ", "KAN GRUBU", "İLAÇ", "DOKTOR", "SEMPTOM", "GİRİŞ TARİHİ", "ÇIKIŞ TARİHİ"
            }
        ));
        muayene_kayit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                muayene_kayitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(muayene_kayit);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_kayit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_guncelle)
                        .addGap(18, 18, 18)
                        .addComponent(btn_resetle, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_sil)
                        .addGap(90, 90, 90)
                        .addComponent(btn_kayit1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btn_yazdir))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hasta_semptom)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(hasta_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(hasta_adsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(hasta_giristarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hasta_cıkıstarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(hasta_ilac, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(hasta_dogumt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel16)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(hasta_muayene, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 1, Short.MAX_VALUE)
                                        .addComponent(cmb_kangrubu, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(226, 226, 226))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11)
                            .addComponent(hasta_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hasta_adsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(hasta_giristarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cmb_kangrubu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(hasta_dogumt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(hasta_muayene, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(hasta_ilac, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(hasta_cıkıstarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hasta_semptom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(31, 31, 31)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_kayit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_resetle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_yazdir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_kayit1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setOpaque(false);

        jLabel28.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel28.setText("TC :");

        btn_tcbul.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_tcbul.setText("BUL");
        btn_tcbul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tcbulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addGap(12, 12, 12)
                .addComponent(tc_arama, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_tcbul)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(btn_tcbul)
                    .addComponent(tc_arama))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_oncekisayfa, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addComponent(btn_onceki_sayfa2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_oncekisayfa, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_onceki_sayfa2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(200, 10, 920, 630);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ıcon/Medical+Banner.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 1500, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_oncekisayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oncekisayfaActionPerformed
        this.dispose();
        doktor_islem_secim l = new doktor_islem_secim();
        l.setVisible(true);
    }//GEN-LAST:event_btn_oncekisayfaActionPerformed

    private void btn_onceki_sayfa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_onceki_sayfa2ActionPerformed
        this.dispose();
        login l = new login();
        l.setVisible(true);
    }//GEN-LAST:event_btn_onceki_sayfa2ActionPerformed

    public void Insert() throws SQLException {
        Connection conn = null;
        ResultSet rs = null;

        try {
            conn = db.connection_db();
            String sql = "INSERT INTO MUAYENE "
                    + "values(?,?,?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, hasta_tc.getText());
              try {
                int i;
                i = Integer.parseInt(hasta_tc.getText());
                hasta_tc.setText("");

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "LÜTFEN TC KISMINA 11 HANELİ RAKAM GİRİNİZ!");
                hasta_tc.setText(null);
                hasta_tc.setFocusable(true);
            }
            pst.setString(2, hasta_adsoyad.getText());
            pst.setString(3, hasta_dogumt.getText());
            pst.setString(4, (String) cmb_kangrubu.getSelectedItem());
            pst.setString(5, hasta_ilac.getText());
            pst.setString(6, hasta_muayene.getText());
            pst.setString(7, hasta_semptom.getText());
            pst.setString(8, hasta_giristarihi.getText());
            pst.setString(9, hasta_cıkıstarihi.getText());

            pst.executeUpdate();
            retrievetableMUAYENE();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            JOptionPane.showMessageDialog(null, "KAYIT BAŞARILI.");
            pst.close();
            conn.close();
        }
    }

    private void btn_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silActionPerformed
        if (!(hasta_tc.getText()).equals("")) {
            try {
                conn = db.connection_db();
                String sql = "DELETE FROM MUAYENE WHERE TC=?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, hasta_tc.getText());
                try {
                int i;
                i = Integer.parseInt(hasta_tc.getText());
                hasta_tc.setText("");

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "LÜTFEN TC KISMINA 11 HANELİ RAKAM GİRİNİZ!");
                hasta_tc.setText(null);
                hasta_tc.setFocusable(true);
            }
                pst.execute();
                retrievetableMUAYENE();
                resetle();
                JOptionPane.showMessageDialog(null, "KAYIT SİLİNMİŞTİR !");
            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e);

            } finally {
                try {

                    conn.close();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "SİLMEK İSTEDİĞİNİZ KAYDI SEÇİNİZ !");
        }
    }//GEN-LAST:event_btn_silActionPerformed

    private void btn_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guncelleActionPerformed
        try {
            conn = db.connection_db();
            String TC = hasta_tc.getText();
            String ad_soyad = hasta_adsoyad.getText();
            String dogumt = hasta_dogumt.getText();
            String kangrubu = (String) cmb_kangrubu.getSelectedItem();
            String ilac = hasta_ilac.getText();
            String muayene = hasta_muayene.getText();
            String giristarih = hasta_giristarihi.getText();
            String cıkıstarih = hasta_cıkıstarihi.getText();
            String semptom = hasta_semptom.getText();
            String sql = "UPDATE MUAYENE SET  TC='" + TC + "',ADSOYAD='" + ad_soyad + "',DOGUMTARIH='" + dogumt + "',"
                    + "KANGRUBU='" + kangrubu + "',ILAÇ='" + ilac + "',MUAYENE='" + muayene + "',"
                    + "SEMPTOM='" + semptom + "',GIRISTARIHI='" + giristarih + "',CIKISTARIHI='" + cıkıstarih + "' WHERE TC='" + TC + "'";
            pst = conn.prepareStatement(sql);
            pst.execute();
            retrievetableMUAYENE();

            JOptionPane.showMessageDialog(null, "KAYIT GÜNCELLENMİŞTİR.");
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "KAYIT GÜNCELLENEMİŞTİR !");
            JOptionPane.showMessageDialog(null, e);

        } finally {
            try {

                conn.close();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e);

            }

        }
    }//GEN-LAST:event_btn_guncelleActionPerformed

    private void resetle() {
        hasta_tc.setText("");
        hasta_adsoyad.setText("");
        hasta_dogumt.setText("");
        hasta_ilac.setText("");
        cmb_kangrubu.setSelectedItem(null);
        hasta_giristarihi.setText("");
        hasta_cıkıstarihi.setText("");
        hasta_muayene.setText("");
        hasta_semptom.setText("");
    }

    private void btn_resetleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetleActionPerformed

        resetle();
        retrievetableMUAYENE();

    }//GEN-LAST:event_btn_resetleActionPerformed

    private void muayene_kayitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_muayene_kayitMouseClicked
        int i = muayene_kayit.getSelectedRow();
        TableModel model = muayene_kayit.getModel();
        hasta_tc.setText(model.getValueAt(i, 0).toString());
        hasta_adsoyad.setText(model.getValueAt(i, 1).toString());
        hasta_dogumt.setText(model.getValueAt(i, 2).toString());
        cmb_kangrubu.setSelectedItem(model.getValueAt(i, 3));
        hasta_ilac.setText(model.getValueAt(i, 4).toString());
        hasta_muayene.setText(model.getValueAt(i, 5).toString());
        hasta_semptom.setText(model.getValueAt(i, 6).toString());
        hasta_giristarihi.setText(model.getValueAt(i, 7).toString());
        hasta_cıkıstarihi.setText(model.getValueAt(i, 8).toString());
    }//GEN-LAST:event_muayene_kayitMouseClicked

    private void btn_tcbulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tcbulActionPerformed
        String HastaTC = "";
         try {
                int i;
                i = Integer.parseInt(tc_arama.getText());
                tc_arama.setText("");

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "LÜTFEN 11 HANELİ RAKAM GİRİNİZ!");
                tc_arama.setText(null);
                tc_arama.setFocusable(true);
            }
        String data = "";

        try {
            conn = Helper.db.connection_db();
            String sql = "SELECT * FROM MUAYENE WHERE TC=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, tc_arama.getText());
            rs = pst.executeQuery();

            if (rs.next()) {
                HastaTC = rs.getString("TC");
                JOptionPane.showMessageDialog(null, "TC BULUNDU.");

            } else {
                JOptionPane.showMessageDialog(null, "TC BULUNAMADI !");
            }
        } catch (Exception ex) {

        }
        try {
            conn.close();
            retrievetable(HastaTC);
        } catch (Exception ex) {

        }

        try {
            conn = Helper.db.connection_db();
            String sql = "SELECT * FROM MUAYENE WHERE TC=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, tc_arama.getText());
            rs = pst.executeQuery();
            while (rs.next()) {
                data = rs.getString("TC");
                hasta_tc.setText(data);
                data = rs.getString("ADSOYAD");
                hasta_adsoyad.setText(data);
                data = rs.getString("DOGUMTARIH");
                hasta_dogumt.setText(data);
                data = rs.getString("KANGRUBU");
                cmb_kangrubu.setSelectedItem(data);
                data = rs.getString("ILAÇ");
                hasta_ilac.setText(data);
                data = rs.getString("MUAYENE");
                hasta_muayene.setText(data);
                data = rs.getString("SEMPTOM");
                hasta_semptom.setText(data);
                data = rs.getString("GIRISTARIHI");
                hasta_giristarihi.setText(data);
                data = rs.getString("CIKISTARIHI");
                hasta_cıkıstarihi.setText(data);

            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_btn_tcbulActionPerformed

    private void btn_kayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayitActionPerformed
        try {
            if (hasta_tc.getText().length() == 0
                    || hasta_adsoyad.getText().length() == 0
                    || hasta_dogumt.getText().length() == 0
                    || cmb_kangrubu.getSelectedIndex() == 0
                    || hasta_ilac.getText().length() == 0
                    || hasta_muayene.getText().length() == 0
                    || hasta_semptom.getText().length() == 0
                    || hasta_giristarihi.getText().length() == 0
                    || hasta_cıkıstarihi.getText().length() == 0) {

                helper.bosluk("fill");

            } else {
                Insert();
                retrievetableMUAYENE();
                resetle();

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_btn_kayitActionPerformed

    private void btn_yazdirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_yazdirActionPerformed
        PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setJobName(" Print Component ");

        pj.setPrintable(new Printable() {
            public int print(Graphics pg, PageFormat pf, int pageNum) {
                if (pageNum > 0) {
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2 = (Graphics2D) pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                jTextArea1.paint(g2);
                return Printable.PAGE_EXISTS;
            }
        });

        if (pj.printDialog() == false) {
            return;
        }

        try {
            pj.print();
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btn_yazdirActionPerformed

    private void btn_kayit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayit1ActionPerformed
    textarea();
    }//GEN-LAST:event_btn_kayit1ActionPerformed

    public void textarea() {
        if (hasta_semptom.getText().length() > 0) {
            jTextArea1.append(" REÇETE :  \n\n"
                    + "TC              : \t" + hasta_tc.getText()
                    + "\n AD - SOYAD   : \t" + hasta_adsoyad.getText()
                    + "\n DOĞUM TARİHİ :" + hasta_dogumt.getText()
                    + "\n KAN GRUBU    : " + cmb_kangrubu.getSelectedItem()
                    + "\n İLAÇ         : \t" + hasta_ilac.getText()
                    + "\n DOKTOR       : \t" + hasta_muayene.getText()
                    + "\n GİRİŞ TARİHİ : " + hasta_giristarihi.getText()
                    + "\n ÇIKIŞ TARİHİ : " + hasta_cıkıstarihi.getText()
                    + "\n SEMPTOM      : \t" + hasta_semptom.getText());
        } else {
            helper.bosluk("fill");
        }
    }

    public class TextAreaPrintStream extends PrintStream {

        //The JTextArea to wich the output stream will be redirected.
        private JTextArea textArea;

        /**
         * Method TextAreaPrintStream The constructor of the class.
         *
         * @param the JTextArea to wich the output stream will be redirected.
         * @param a standard output stream (needed by super method)
     *
         */
        public TextAreaPrintStream(JTextArea area, OutputStream out) {
            super(out);
            textArea = area;
        }

        public void println(String string) {
            textArea.append(string + "\n");
        }

        public void print(String string) {
            textArea.append(string);
        }
    }
    
    
    private void cinsiye_doldur(javax.swing.JComboBox<String> cmb_cinsiye, String sql2) {
        try {
            conn = db.connection_db();
            String sql = "SELECT * FROM CİNSİYET";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                cmb_cinsiye.addItem(rs.getString("Cinsiyet"));
            }
        } catch (Exception ex) {

        } finally {
            try {
                conn.close();
            } catch (Exception ex) {

            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doktor_islem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doktor_islem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doktor_islem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doktor_islem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doktor_islem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guncelle;
    private javax.swing.JButton btn_kayit;
    private javax.swing.JButton btn_kayit1;
    private javax.swing.JButton btn_onceki_sayfa2;
    private javax.swing.JButton btn_oncekisayfa;
    private javax.swing.JButton btn_resetle;
    private javax.swing.JButton btn_sil;
    private javax.swing.JButton btn_tcbul;
    private javax.swing.JButton btn_yazdir;
    private javax.swing.JComboBox<String> cmb_kangrubu;
    private javax.swing.JTextField hasta_adsoyad;
    private javax.swing.JTextField hasta_cıkıstarihi;
    private javax.swing.JTextField hasta_dogumt;
    private javax.swing.JTextField hasta_giristarihi;
    private javax.swing.JTextField hasta_ilac;
    private javax.swing.JTextField hasta_muayene;
    private javax.swing.JTextField hasta_semptom;
    private javax.swing.JTextField hasta_tc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable muayene_kayit;
    private javax.swing.JTextField tc_arama;
    // End of variables declaration//GEN-END:variables
}
