package hastatakipsist;

import Helper.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class sekreter_idrar_tahlil extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int columnsNumber = 0;
    
    

    public sekreter_idrar_tahlil() {
        initComponents();
        retrievetableIdrar2();
        
        setSize(1500,700);
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

    }

    private void retrievetableIdrar(String TC) {
        try {
            DefaultTableModel tbl = (DefaultTableModel) tbl_idrar.getModel();
            while (tbl.getRowCount() > 0) {
                tbl.removeRow(0);
            }

            conn = Helper.db.connection_db();
            String sql = "SELECT * FROM IdrarTahlil WHERE TC='" + TC + "'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            columnsNumber = rsmd.getColumnCount();

            String[] data = new String[columnsNumber];
            while (rs.next()) {
                for (int i = 0; i < data.length; i++) {
                    data[i] = rs.getString(i + 1);
                }

                DefaultTableModel tblModel = (DefaultTableModel) tbl_idrar.getModel();
                tblModel.addRow(data);
            }
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, ex);

        } finally {
            try {
                conn.close();
            } catch (Exception ex) {

                JOptionPane.showMessageDialog(null, ex);

            }
        }

    }

    private void retrievetableIdrar2() {
        try {
            DefaultTableModel tbl = (DefaultTableModel) tbl_idrar.getModel();
            while (tbl.getRowCount() > 0) {
                tbl.removeRow(0);
            }

            conn = Helper.db.connection_db();
            String sql = "SELECT * FROM IdrarTahlil";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            columnsNumber = rsmd.getColumnCount();

            String[] data = new String[columnsNumber];
            while (rs.next()) {
                for (int i = 0; i < data.length; i++) {
                    data[i] = rs.getString(i + 1);
                }

                DefaultTableModel tblModel = (DefaultTableModel) tbl_idrar.getModel();
                tblModel.addRow(data);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        } finally {
            try {
                conn.close();
            } catch (Exception ex) {

            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_idrar = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hasta_tc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_renk = new javax.swing.JTextField();
        txt_tarih = new javax.swing.JTextField();
        txt_glukoz = new javax.swing.JTextField();
        txt_protein = new javax.swing.JTextField();
        txt_ph = new javax.swing.JTextField();
        txt_dansite = new javax.swing.JTextField();
        txt_bilirubin = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_keton = new javax.swing.JTextField();
        btn_kayit = new javax.swing.JButton();
        btn_sil = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_urobili = new javax.swing.JTextField();
        txt_gorunum = new javax.swing.JTextField();
        btn_resetle = new javax.swing.JButton();
        txt_nitrit = new javax.swing.JTextField();
        btn_güncelle = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        tc_arama = new javax.swing.JTextField();
        btn_tcbul = new javax.swing.JButton();
        btn_onceki_sayfa = new javax.swing.JButton();
        btn_onceki_sayfa1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setOpaque(false);

        jScrollPane4.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jScrollPane4.setEnabled(false);

        tbl_idrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "TC", "Tarih", "Renk", "Görünüm", "Dansite", "pH", "Protein", "Glukoz", "Bilirubin", "Ürobilinojen", "Keton", "Nitrit"
            }
        ));
        tbl_idrar.setAutoscrolls(false);
        tbl_idrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_idrar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tbl_idrar.setIntercellSpacing(new java.awt.Dimension(1, 4));
        tbl_idrar.setOpaque(false);
        tbl_idrar.setRequestFocusEnabled(false);
        tbl_idrar.getTableHeader().setReorderingAllowed(false);
        tbl_idrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_idrarMouseClicked(evt);
            }
        });
        tbl_idrar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbl_idrarPropertyChange(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_idrar);

        jPanel4.setOpaque(false);

        jLabel20.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel20.setText("LABORATUVAR İDRAR TAHLİL SONUCU EKLEME");

        jPanel5.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("pH:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Tarih:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Protein:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("TC:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Dansite:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Renk:");

        hasta_tc.setToolTipText("");
        hasta_tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasta_tcActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Görünüm:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Glukoz:");

        txt_renk.setToolTipText("");

        txt_tarih.setToolTipText("");

        txt_glukoz.setToolTipText("");

        txt_protein.setToolTipText("");

        txt_ph.setToolTipText("");

        txt_dansite.setToolTipText("");

        txt_bilirubin.setToolTipText("");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Ürobilinojen:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Nitrit:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Bilirubin:");

        txt_keton.setToolTipText("");

        btn_kayit.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_kayit.setText("KAYIT ");
        btn_kayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayitActionPerformed(evt);
            }
        });

        btn_sil.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_sil.setText("SİL");
        btn_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silActionPerformed(evt);
            }
        });

        jLabel1.setText("Keton:");

        txt_urobili.setToolTipText("");

        txt_gorunum.setToolTipText("");

        btn_resetle.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_resetle.setText("RESETLE");
        btn_resetle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetleActionPerformed(evt);
            }
        });

        txt_nitrit.setToolTipText("");

        btn_güncelle.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_güncelle.setText("GÜNCELLE");
        btn_güncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_güncelleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hasta_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ph, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_keton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nitrit, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(btn_güncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(btn_resetle, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(btn_sil))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_protein, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                .addComponent(txt_renk, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8))
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(txt_glukoz, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel16)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_bilirubin, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_gorunum, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_dansite, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_urobili, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(btn_kayit, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasta_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txt_renk, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_dansite, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gorunum, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ph, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txt_protein, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_glukoz, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txt_bilirubin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel13)
                    .addComponent(txt_urobili, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_keton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel1)
                    .addComponent(txt_nitrit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_kayit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_resetle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_güncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(379, 379, 379))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel20))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jPanel3.setOpaque(false);

        jLabel28.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel28.setText("TC :");

        btn_tcbul.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_tcbul.setText("BUL");
        btn_tcbul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tcbulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tc_arama, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_tcbul)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(tc_arama)
                    .addComponent(btn_tcbul))
                .addContainerGap())
        );

        btn_onceki_sayfa.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_onceki_sayfa.setText("Önceki sayfa");
        btn_onceki_sayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_onceki_sayfaActionPerformed(evt);
            }
        });

        btn_onceki_sayfa1.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_onceki_sayfa1.setText("OTURUMU KAPAT");
        btn_onceki_sayfa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_onceki_sayfa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_onceki_sayfa, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_onceki_sayfa1)
                        .addGap(48, 48, 48)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_onceki_sayfa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_onceki_sayfa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(170, 30, 1159, 611);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ıcon/Medical+Banner.jpg"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(0, 0, 1500, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_idrarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbl_idrarPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_idrarPropertyChange

    private void hasta_tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasta_tcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasta_tcActionPerformed

    private void btn_kayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayitActionPerformed
        if (hasta_tc.getText().length() == 0
                || txt_tarih.getText().length() == 0
                || txt_renk.getText().length() == 0
                || txt_dansite.getText().length() == 0
                || txt_ph.getText().length() == 0
                || txt_protein.getText().length() == 0
                || txt_glukoz.getText().length() == 0
                || txt_bilirubin.getText().length() == 0
                || txt_urobili.getText().length() == 0
                || txt_keton.getText().length() == 0
                || txt_nitrit.getText().length() == 0) {

            helper.bosluk("fill");

        } else {
            try {
                String sql = "INSERT INTO IdrarTahlil "
                        + "values(?,?,?,?,?,?,?,?,?,?,?,?)";
                conn = db.connection_db();
                pst = conn.prepareStatement(sql);
                pst.setString(1, hasta_tc.getText());
                pst.setString(2, txt_tarih.getText());
                pst.setString(3, txt_renk.getText());
                pst.setString(4, txt_gorunum.getText());
                pst.setString(5, txt_dansite.getText());
                pst.setString(6, txt_ph.getText());
                pst.setString(7, txt_protein.getText());
                pst.setString(8, txt_glukoz.getText());
                pst.setString(9, txt_bilirubin.getText());
                pst.setString(10, txt_urobili.getText());
                pst.setString(11, txt_keton.getText());
                pst.setString(12, txt_nitrit.getText());
                pst.executeUpdate();
                retrievetableIdrar2();

                JOptionPane.showMessageDialog(null, "KAYIT BAŞARIYLA EKLENDİ.");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } finally {
                try {
                    resetle();
                    pst.close();
                    conn.close();

                } catch (Exception e) {
                }
            }
        }
    }//GEN-LAST:event_btn_kayitActionPerformed

    private void btn_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silActionPerformed
        if (!(hasta_tc.getText()).equals("")) {
            try {
                conn = db.connection_db();
                String sql = "DELETE FROM IdrarTahlil WHERE TC=?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, hasta_tc.getText());
                pst.execute();
                retrievetableIdrar2();
                resetle();
                JOptionPane.showMessageDialog(null, "KAYIT SİLİNMİŞTİR !");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } finally {
                try {

                    conn.close();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "SİLMEK İSTEDİĞİNİZ KAYDI SEÇİNİZ !");
        }
    }//GEN-LAST:event_btn_silActionPerformed

    private void btn_tcbulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tcbulActionPerformed
        String HastaTC = "";
        String data = "";
        try {
            conn = Helper.db.connection_db();
            String sql = "SELECT * FROM IdrarTahlil WHERE TC=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, tc_arama.getText());
            rs = pst.executeQuery();

            if (rs.next()) {
                HastaTC = rs.getString("TC");
                JOptionPane.showMessageDialog(null, "TC BULUNDU.");

            } else {
                JOptionPane.showMessageDialog(null, "TC BULUNAMADI !");
            }
        } catch (Exception ex) {

        }
        try {
            conn.close();
            retrievetableIdrar(HastaTC);
        } catch (Exception ex) {

        }

        try {
            conn = Helper.db.connection_db();
            String sql = "SELECT * FROM IdrarTahlil WHERE TC=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, tc_arama.getText());
            rs = pst.executeQuery();
            while (rs.next()) {
                data = rs.getString("TC");
                hasta_tc.setText(data);
                data = rs.getString("Tarih");
                txt_tarih.setText(data);
                data = rs.getString("Renk");
                txt_renk.setText(data);
                data = rs.getString("Görünüm");
                txt_gorunum.setText(data);
                data = rs.getString("Dansite");
                txt_dansite.setText(data);
                data = rs.getString("pH");
                txt_ph.setText(data);
                data = rs.getString("Protein");
                txt_protein.setText(data);
                data = rs.getString("Glukoz");
                txt_glukoz.setText(data);
                data = rs.getString("Bilirubin");
                txt_bilirubin.setText(data);
                data = rs.getString("Ürobilinojen");
                txt_urobili.setText(data);
                data = rs.getString("Keton");
                txt_keton.setText(data);
                data = rs.getString("Nitrit");
                txt_nitrit.setText(data);
            }
        } catch (Exception ex) {

        }

    }//GEN-LAST:event_btn_tcbulActionPerformed

    public void resetle() {
        tc_arama.setText("");
        hasta_tc.setText("");
        txt_tarih.setText("");
        txt_renk.setText("");
        txt_dansite.setText("");
        txt_gorunum.setText("");
        txt_ph.setText("");
        txt_protein.setText("");
        txt_glukoz.setText("");
        txt_bilirubin.setText("");
        txt_urobili.setText("");
        txt_keton.setText("");
        txt_nitrit.setText("");
    }
    private void btn_resetleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetleActionPerformed

        resetle();
        retrievetableIdrar2();

    }//GEN-LAST:event_btn_resetleActionPerformed

    private void btn_onceki_sayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_onceki_sayfaActionPerformed
        this.dispose();
        sekreter_islem_secme s = new sekreter_islem_secme();
        s.setVisible(true);
    }//GEN-LAST:event_btn_onceki_sayfaActionPerformed

    private void btn_onceki_sayfa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_onceki_sayfa1ActionPerformed
        this.dispose();
        login l = new login();
        l.setVisible(true);
    }//GEN-LAST:event_btn_onceki_sayfa1ActionPerformed

    private void tbl_idrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_idrarMouseClicked
    int i = tbl_idrar.getSelectedRow();
        TableModel model = tbl_idrar.getModel();
        hasta_tc.setText(model.getValueAt(i, 0).toString());
        txt_tarih.setText(model.getValueAt(i, 1).toString());
        txt_renk.setText(model.getValueAt(i, 2).toString());
        txt_gorunum.setText(model.getValueAt(i, 3).toString());
        txt_dansite.setText(model.getValueAt(i, 4).toString());
        txt_ph.setText(model.getValueAt(i, 5).toString());
        txt_protein.setText(model.getValueAt(i, 6).toString());
        txt_glukoz.setText(model.getValueAt(i, 7).toString());
        txt_bilirubin.setText(model.getValueAt(i, 8).toString());
        txt_urobili.setText(model.getValueAt(i, 9).toString());
        txt_keton.setText(model.getValueAt(i, 10).toString());
        txt_nitrit.setText(model.getValueAt(i, 11).toString());
    }//GEN-LAST:event_tbl_idrarMouseClicked

    private void btn_güncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_güncelleActionPerformed
    
       try {
            conn = db.connection_db();
            String TC = hasta_tc.getText();
            String tarih = txt_tarih.getText();
            String renk = txt_renk.getText();
            String gorunum = txt_gorunum.getText();
            String dansite = txt_dansite.getText();
            String ph = txt_ph.getText();
            String protein = txt_protein.getText();
            String glukoz = txt_glukoz.getText();
            String bilirubin = txt_bilirubin.getText();
            String urobili = txt_urobili.getText();
            String keton = txt_keton.getText();
            String nitrit = txt_nitrit.getText();

            String sql = "UPDATE IdrarTahlil SET  TC='" + TC + "',Tarih='" + tarih + "',Renk='" + renk + "',"
                    + "Görünüm='" + gorunum + "',Dansite='" + dansite + "',pH='" + ph + "',"
                    + "Protein='" + protein + "',Glukoz='" + glukoz + "',"
                    + "Bilirubin='" + bilirubin + "',Ürobilinojen='" + urobili + "',"
                    + "Keton='" + keton + "',Nitrit='" + nitrit + "' WHERE TC='" + TC + "'";
            pst = conn.prepareStatement(sql);
            pst.execute();
            retrievetableIdrar2();
            JOptionPane.showMessageDialog(null, "KAYIT GÜNCELLENMİŞTİR.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        } finally {
            try {

                conn.close();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e);

            }

        }     

    }//GEN-LAST:event_btn_güncelleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sekreter_idrar_tahlil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sekreter_idrar_tahlil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sekreter_idrar_tahlil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sekreter_idrar_tahlil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sekreter_idrar_tahlil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_güncelle;
    private javax.swing.JButton btn_kayit;
    private javax.swing.JButton btn_onceki_sayfa;
    private javax.swing.JButton btn_onceki_sayfa1;
    private javax.swing.JButton btn_resetle;
    private javax.swing.JButton btn_sil;
    private javax.swing.JButton btn_tcbul;
    private javax.swing.JTextField hasta_tc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbl_idrar;
    private javax.swing.JTextField tc_arama;
    private javax.swing.JTextField txt_bilirubin;
    private javax.swing.JTextField txt_dansite;
    private javax.swing.JTextField txt_glukoz;
    private javax.swing.JTextField txt_gorunum;
    private javax.swing.JTextField txt_keton;
    private javax.swing.JTextField txt_nitrit;
    private javax.swing.JTextField txt_ph;
    private javax.swing.JTextField txt_protein;
    private javax.swing.JTextField txt_renk;
    private javax.swing.JTextField txt_tarih;
    private javax.swing.JTextField txt_urobili;
    // End of variables declaration//GEN-END:variables
}
