package hastatakipsist;

import Helper.*;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class sekreter_islem extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int columnsNumber = 0;

    public sekreter_islem() {
        initComponents();
        hasta_tc.setEnabled(true);
        retrievetableHASTA2();
        
        setSize(1500,700);
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        try {
            conn = db.connection_db();
            String sql = "SELECT * FROM CİNSİYET";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                cmb_cinsiye.addItem(rs.getString("Cinsiyet"));
            }
        } catch (Exception ex) {

        } finally {
            try {
                conn.close();
            } catch (Exception ex) {

            }
        }

        try {
            conn = db.connection_db();
            String sql = "SELECT * FROM KANGRUBU";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                cmb_kangrubu.addItem(rs.getString("KanGrubu"));
            }
        } catch (Exception ex) {

        } finally {
            try {
                conn.close();
            } catch (Exception ex) {

            }
        }

        try {
            conn = db.connection_db();
            String sql = "SELECT * FROM SSK";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                cmb_sigorta.addItem(rs.getString("Sigorta"));
            }
        } catch (Exception ex) {

        } finally {
            try {
                conn.close();
            } catch (Exception ex) {

            }
        }

    }

    private void retrievetableHASTA(String TC) {
        try {
            DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
            while (table.getRowCount() > 0) {
                table.removeRow(0);
            }
            conn = db.connection_db();
            String sql = "SELECT * FROM HASTA WHERE TC='" + TC + "'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            columnsNumber = rsmd.getColumnCount();

            String[] data = new String[columnsNumber];
            while (rs.next()) {
                for (int i = 0; i < data.length; i++) {
                    data[i] = rs.getString(i + 1);
                }

                DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                tableModel.addRow(data);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                conn.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }

    private void retrievetableHASTA2() {
        try {
            DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
            while (table.getRowCount() > 0) {
                table.removeRow(0);
            }
            conn = db.connection_db();
            String sql = "select * from HASTA";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            columnsNumber = rsmd.getColumnCount();

            String[] data = new String[columnsNumber];
            while (rs.next()) {
                for (int i = 0; i < data.length; i++) {
                    data[i] = rs.getString(i + 1);
                }

                DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                tableModel.addRow(data);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                conn.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        JTable1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        tc_arama = new javax.swing.JTextField();
        btn_tcbul = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hasta_tc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        hasta_dogumt = new javax.swing.JTextField();
        hasta_adsoyad = new javax.swing.JTextField();
        hasta_anneadi = new javax.swing.JTextField();
        hasta_adres = new javax.swing.JTextField();
        hasta_tel = new javax.swing.JTextField();
        hasta_dogumy = new javax.swing.JTextField();
        hasta_babaadi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        hasta_il = new javax.swing.JTextField();
        hasta_ilce = new javax.swing.JTextField();
        hasta_eposta = new javax.swing.JTextField();
        btn_kayit = new javax.swing.JButton();
        cmb_kangrubu = new javax.swing.JComboBox<>();
        cmb_sigorta = new javax.swing.JComboBox<>();
        btn_guncelle = new javax.swing.JButton();
        btn_sil = new javax.swing.JButton();
        btn_idrar_reset = new javax.swing.JButton();
        cmb_cinsiye = new javax.swing.JComboBox<>();
        btn_onceki_sayfa = new javax.swing.JButton();
        btn_oturumukapat = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setOpaque(false);

        JTable1.setToolTipText("");
        JTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JTable1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        JTable1.setEnabled(false);
        JTable1.setName(""); // NOI18N

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TC", "ADSOYAD", "DOGUMTARIH", "DOGUMYERI", "CINSIYET", "TELEFON", "ADRES", "ANNE ADI", "BABA ADI", "IL", "ILCE", "EPOSTA", "SİGORTA", "KAN GRUBU"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        JTable1.setViewportView(jTable1);

        jPanel3.setOpaque(false);

        jLabel28.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel28.setText("TC :");

        tc_arama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tc_aramaActionPerformed(evt);
            }
        });

        btn_tcbul.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_tcbul.setText("BUL");
        btn_tcbul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tcbulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tc_arama, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_tcbul)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(btn_tcbul))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tc_arama, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel4.setOpaque(false);

        jLabel20.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel20.setText("HASTA KAYIT VE  GÜNCELLEME İŞLEMİ ");

        jPanel5.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("ADRES:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("AD SOYAD:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("ANNE ADI:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("TC:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("CİNSİYET:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("TEL:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("DOĞUM TARİHİ:");

        hasta_tc.setToolTipText("");
        hasta_tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasta_tcActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("DOĞUM YERİ:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("BABA ADI:");

        hasta_dogumt.setText("GG.AA.YYYY");
        hasta_dogumt.setToolTipText("");

        hasta_adsoyad.setToolTipText("");

        hasta_anneadi.setToolTipText("");

        hasta_adres.setToolTipText("");

        hasta_tel.setToolTipText("");

        hasta_dogumy.setToolTipText("");

        hasta_babaadi.setToolTipText("");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("İL:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("İLÇE:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("E-POSTA:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("KAN GRUBU:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("SİGORTA:");

        hasta_il.setToolTipText("");

        hasta_ilce.setToolTipText("");

        hasta_eposta.setToolTipText("");

        btn_kayit.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_kayit.setText("KAYIT ");
        btn_kayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayitActionPerformed(evt);
            }
        });

        cmb_kangrubu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEÇİNİZ" }));

        cmb_sigorta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEÇİNİZ" }));

        btn_guncelle.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_guncelle.setText("GÜNCELLE");
        btn_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guncelleActionPerformed(evt);
            }
        });

        btn_sil.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_sil.setText("SİL");
        btn_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silActionPerformed(evt);
            }
        });

        btn_idrar_reset.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_idrar_reset.setText("RESETLE");
        btn_idrar_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_idrar_resetActionPerformed(evt);
            }
        });

        cmb_cinsiye.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEÇİNİZ" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(hasta_il))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hasta_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hasta_tc)))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel11))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hasta_adres, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(hasta_adsoyad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hasta_ilce)))
                    .addComponent(btn_kayit, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(hasta_eposta)
                                    .addGap(39, 39, 39)
                                    .addComponent(jLabel17))
                                .addComponent(jLabel12)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(hasta_dogumt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel8)))
                            .addComponent(hasta_anneadi, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hasta_dogumy, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hasta_babaadi, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_sigorta, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb_kangrubu, 0, 128, Short.MAX_VALUE)
                            .addComponent(cmb_cinsiye, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btn_guncelle))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(btn_idrar_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addComponent(btn_sil)))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasta_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(hasta_adsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(hasta_dogumy, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasta_dogumt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cmb_cinsiye, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(hasta_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(hasta_adres, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(hasta_anneadi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(hasta_babaadi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_kangrubu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(hasta_il, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(hasta_ilce, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(hasta_eposta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(cmb_sigorta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_kayit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_idrar_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(436, 436, 436))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_guncelle, btn_kayit});

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(291, 291, 291))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(1, 1, 1)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btn_onceki_sayfa.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_onceki_sayfa.setText("Önceki sayfa");
        btn_onceki_sayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_onceki_sayfaActionPerformed(evt);
            }
        });

        btn_oturumukapat.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_oturumukapat.setText("OTURUMU KAPAT");
        btn_oturumukapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oturumukapatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_onceki_sayfa, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(328, 328, 328)
                        .addComponent(btn_oturumukapat))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTable1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_onceki_sayfa, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_oturumukapat, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JTable1.getAccessibleContext().setAccessibleName("");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ıcon/Medical+Banner.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel21)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btn_tcbulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tcbulActionPerformed
        String HastaTC = "";
        String data = "";
        try {
            conn = db.connection_db();
            String sql = "SELECT * FROM HASTA WHERE TC=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, tc_arama.getText());
            rs = pst.executeQuery();

            if (rs.next()) {
                HastaTC = rs.getString("TC");
                JOptionPane.showMessageDialog(null, "TC BULUNDU");

            } else {
                JOptionPane.showMessageDialog(null, "TC BULUNAMADI ! ");
            }
        } catch (Exception ex) {

        }
        try {
            conn.close();
            retrievetableHASTA(HastaTC);
        } catch (Exception ex) {

        }

        try {
            conn = db.connection_db();
            String sql = "SELECT * FROM HASTA WHERE TC=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, tc_arama.getText());
            rs = pst.executeQuery();
            while (rs.next()) {
                data = rs.getString("TC");
                hasta_tc.setText(data);
                data = rs.getString("ADSOYAD");
                hasta_adsoyad.setText(data);
                data = rs.getString("DOGUMTARIH");
                hasta_dogumt.setText(data);
                data = rs.getString("DOGUMYERI");
                hasta_dogumy.setText(data);
                data = rs.getString("TELEFON");
                hasta_tel.setText(data);
                data = rs.getString("ADRES");
                hasta_adres.setText(data);
                data = rs.getString("ANNEADI");
                hasta_anneadi.setText(data);
                data = rs.getString("BABAADI");
                hasta_babaadi.setText(data);
                data = rs.getString("IL");
                hasta_il.setText(data);
                data = rs.getString("ILCE");
                hasta_ilce.setText(data);
                data = rs.getString("EPOSTA");
                hasta_eposta.setText(data);
                data = rs.getString("SIGORTA");
                cmb_sigorta.setSelectedItem(data);
                data = rs.getString("KANGRUBU");
                cmb_kangrubu.setSelectedItem(data);
                data = rs.getString("CINSIYET");
                cmb_cinsiye.setSelectedItem(data);
            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btn_tcbulActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        hasta_tc.setText(model.getValueAt(i, 0).toString());
        hasta_adsoyad.setText(model.getValueAt(i, 1).toString());
        hasta_dogumt.setText(model.getValueAt(i, 2).toString());
        hasta_dogumy.setText(model.getValueAt(i, 3).toString());
        cmb_cinsiye.setSelectedItem(model.getValueAt(i, 4));
        hasta_tel.setText(model.getValueAt(i, 5).toString());
        hasta_adres.setText(model.getValueAt(i, 6).toString());
        hasta_anneadi.setText(model.getValueAt(i, 7).toString());
        hasta_babaadi.setText(model.getValueAt(i, 8).toString());
        hasta_il.setText(model.getValueAt(i, 9).toString());
        hasta_ilce.setText(model.getValueAt(i, 10).toString());
        hasta_eposta.setText(model.getValueAt(i, 11).toString());
        cmb_sigorta.setSelectedItem(model.getValueAt(i, 12));
        cmb_kangrubu.setSelectedItem(model.getValueAt(i, 13));

    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guncelleActionPerformed
        try {
            conn = db.connection_db();
            String TC = hasta_tc.getText();
        
            String ad_soyad = hasta_adsoyad.getText();
            String dogumt = hasta_dogumt.getText();
            String dogumy = hasta_dogumy.getText();
            String cinsiyet = (String) cmb_cinsiye.getSelectedItem();
            String tel = hasta_tel.getText();
            String adres = hasta_adres.getText();
            String anneadı = hasta_anneadi.getText();
            String babaadı = hasta_babaadi.getText();
            String il = hasta_il.getText();
            String ilce = hasta_ilce.getText();
            String eposta = hasta_eposta.getText();
            String sigorta = (String) cmb_sigorta.getSelectedItem();
            String kangrubu = (String) cmb_kangrubu.getSelectedItem();

            String sql = "UPDATE HASTA SET ADSOYAD='" + ad_soyad + "',DOGUMTARIH='" + dogumt + "',"
                    + "DOGUMYERI='" + dogumy + "',TELEFON='" + tel + "',ADRES='" + adres + "',"
                    + "ANNEADI='" + anneadı + "',BABAADI='" + babaadı + "',IL='" + il + "',ILCE='" + ilce + "',"
                    + "EPOSTA='" + eposta + "' WHERE TC='" + TC + "'";

            
            
            pst = conn.prepareStatement(sql);
            pst.execute();
            retrievetableHASTA2();
            JOptionPane.showMessageDialog(null, "KAYIT GÜNCELLENMİŞTİR.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        } finally {
            try {

                conn.close();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e);

            }

        }


    }//GEN-LAST:event_btn_guncelleActionPerformed

    public void Insert() throws SQLException {

        try {

            conn = db.connection_db();

            String sql = "insert into HASTA "
                    + "values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, hasta_tc.getText());
            pst.setString(2, hasta_adsoyad.getText());
            pst.setString(3, hasta_dogumt.getText());
            pst.setString(4, hasta_dogumy.getText());
            pst.setString(5, (String) cmb_cinsiye.getSelectedItem());
            pst.setString(6, hasta_tel.getText());
            pst.setString(7, hasta_adres.getText());
            pst.setString(8, hasta_anneadi.getText());
            pst.setString(9, hasta_babaadi.getText());
            pst.setString(10, hasta_il.getText());
            pst.setString(11, hasta_ilce.getText());
            pst.setString(12, hasta_eposta.getText());
            pst.setString(13, (String) cmb_sigorta.getSelectedItem());
            pst.setString(14, (String) cmb_kangrubu.getSelectedItem());


            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "KAYIT BAŞARIYLA KAYDEDİLDİ.");
            resetle();

        } catch (Exception e) {

        } finally {
            pst.close();
            conn.close();
        }
    }


    
    private void btn_kayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayitActionPerformed

        try {
            if (hasta_tc.getText().length() == 0
                    || hasta_adsoyad.getText().length() == 0
                    || hasta_dogumt.getText().length() == 0
                    || hasta_dogumy.getText().length() == 0
                    || hasta_tel.getText().length() == 0
                    || hasta_adres.getText().length() == 0
                    || hasta_anneadi.getText().length() == 0
                    || hasta_babaadi.getText().length() == 0
                    || hasta_il.getText().length() == 0
                    || hasta_ilce.getText().length() == 0
                    || cmb_cinsiye.getSelectedIndex() == 0
                    || cmb_kangrubu.getSelectedIndex() == 0
                    || cmb_sigorta.getSelectedIndex() == 0
                    || hasta_eposta.getText().length() == 0) {

                helper.bosluk("fill");

            } else {

                Insert();
                retrievetableHASTA2();

            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_btn_kayitActionPerformed

    private void btn_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silActionPerformed
        if (!(hasta_tc.getText()).equals("")) {
            try {
                conn = db.connection_db();
                String sql = "DELETE FROM HASTA WHERE TC=?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, hasta_tc.getText());
                pst.execute();
                retrievetableHASTA2();
                resetle();
                JOptionPane.showMessageDialog(null, "KAYIT SİLİNMİŞTİR !");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } finally {
                try {

                    conn.close();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "SİLMEK İSTEDİĞİNİZ KAYDI SEÇİNİZ !");
        }
    }//GEN-LAST:event_btn_silActionPerformed

    public void resetle() {
        tc_arama.setText("");
        hasta_tc.setText("");
        hasta_adsoyad.setText("");
        hasta_dogumt.setText("");
        hasta_dogumy.setText("");
        hasta_tel.setText("");
        hasta_adres.setText("");
        hasta_anneadi.setText("");
        hasta_babaadi.setText("");
        hasta_il.setText("");
        hasta_ilce.setText("");
        hasta_eposta.setText("");
        cmb_kangrubu.setSelectedItem(null);
        cmb_sigorta.setSelectedItem(null);
        cmb_cinsiye.setSelectedItem(null);
    }

    private void btn_idrar_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_idrar_resetActionPerformed

        resetle();
        retrievetableHASTA2();

    }//GEN-LAST:event_btn_idrar_resetActionPerformed

    private void btn_onceki_sayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_onceki_sayfaActionPerformed
        this.dispose();
        sekreter_islem_secme d = new sekreter_islem_secme();
        d.setVisible(true);
    }//GEN-LAST:event_btn_onceki_sayfaActionPerformed

    private void btn_oturumukapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oturumukapatActionPerformed
        this.dispose();
        login l = new login();
        l.setVisible(true);
    }//GEN-LAST:event_btn_oturumukapatActionPerformed

    private void hasta_tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasta_tcActionPerformed

    }//GEN-LAST:event_hasta_tcActionPerformed

    private void tc_aramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tc_aramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tc_aramaActionPerformed

    private void cinsiye_doldur(javax.swing.JComboBox<String> cmb_cinsiye, String sql2) {
        try {
            conn = db.connection_db();
            String sql = "SELECT * FROM CİNSİYET";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                cmb_cinsiye.addItem(rs.getString("Cinsiyet"));
            }
        } catch (Exception ex) {

        } finally {
            try {
                conn.close();
            } catch (Exception ex) {

            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sekreter_islem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sekreter_islem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sekreter_islem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sekreter_islem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    sekreter_islem frame = new sekreter_islem();
                    frame.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JTable1;
    private javax.swing.JButton btn_guncelle;
    private javax.swing.JButton btn_idrar_reset;
    private javax.swing.JButton btn_kayit;
    private javax.swing.JButton btn_onceki_sayfa;
    private javax.swing.JButton btn_oturumukapat;
    private javax.swing.JButton btn_sil;
    private javax.swing.JButton btn_tcbul;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmb_cinsiye;
    private javax.swing.JComboBox<String> cmb_kangrubu;
    private javax.swing.JComboBox<String> cmb_sigorta;
    private javax.swing.JTextField hasta_adres;
    private javax.swing.JTextField hasta_adsoyad;
    private javax.swing.JTextField hasta_anneadi;
    private javax.swing.JTextField hasta_babaadi;
    private javax.swing.JTextField hasta_dogumt;
    private javax.swing.JTextField hasta_dogumy;
    private javax.swing.JTextField hasta_eposta;
    private javax.swing.JTextField hasta_il;
    private javax.swing.JTextField hasta_ilce;
    private javax.swing.JTextField hasta_tc;
    private javax.swing.JTextField hasta_tel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tc_arama;
    // End of variables declaration//GEN-END:variables
private String cinsiyet;
}
