package hastatakipsist;

import Helper.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class yonetici_islem_sekreter extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int columnsNumber = 0;

    public yonetici_islem_sekreter() {
        initComponents();
        retrievetableSEKRETER2();
        try {
            conn = db.connection_db();
            String sql = "SELECT * FROM CİNSİYET";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                cmb_cinsiye.addItem(rs.getString("Cinsiyet"));
            }
        } catch (Exception ex) {

        } finally {
            try {
                conn.close();
            } catch (Exception ex) {

            }
        }
        setSize(1500,700);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    private void retrievetableSEKRETER(String SEKRETERID) {
        try {
            DefaultTableModel tbl = (DefaultTableModel) jTable1.getModel();
            while (tbl.getRowCount() > 0) {
                tbl.removeRow(0);
            }

            conn = Helper.db.connection_db();
            String sql = "SELECT * FROM SEKRETERKULLANİCİ WHERE SEKRETERID='" + SEKRETERID + "'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            columnsNumber = rsmd.getColumnCount();

            String[] data = new String[columnsNumber];
            while (rs.next()) {
                for (int i = 0; i < data.length; i++) {
                    data[i] = rs.getString(i + 1);
                }

                DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
                tblModel.addRow(data);
            }
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, ex);

        } finally {
            try {
                conn.close();
            } catch (Exception ex) {

                JOptionPane.showMessageDialog(null, ex);

            }
        }

    }

    private void retrievetableSEKRETER2() {
        try {
            DefaultTableModel tbl = (DefaultTableModel) jTable1.getModel();
            while (tbl.getRowCount() > 0) {
                tbl.removeRow(0);
            }

            conn = Helper.db.connection_db();
            String sql = "SELECT * FROM SEKRETERKULLANİCİ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            columnsNumber = rsmd.getColumnCount();

            String[] data = new String[columnsNumber];
            while (rs.next()) {
                for (int i = 0; i < data.length; i++) {
                    data[i] = rs.getString(i + 1);
                }

                DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
                tblModel.addRow(data);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        } finally {
            try {
                conn.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_onceki_sayfa = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        txt_id_bul = new javax.swing.JTextField();
        btn_id_bul = new javax.swing.JButton();
        btn_oturumu_kapat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        s_dt = new javax.swing.JTextField();
        s_id = new javax.swing.JTextField();
        s_dy = new javax.swing.JTextField();
        s_eposta = new javax.swing.JTextField();
        s_adsoyad = new javax.swing.JTextField();
        s_tel = new javax.swing.JTextField();
        btn_silme = new javax.swing.JButton();
        btn_guncelle = new javax.swing.JButton();
        btn_kayit = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        s_adres = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        btn_resetle = new javax.swing.JButton();
        sifregoster = new javax.swing.JCheckBox();
        s_sifre = new javax.swing.JPasswordField();
        cmb_cinsiye = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setOpaque(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "AD SOYAD", "E-POSTA", "TEL", "SIFRE", "ADRES", "DOGUM TARİHİ", "DOGUM YERİ", "CİNSİYET"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btn_onceki_sayfa.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_onceki_sayfa.setText("Önceki sayfa");
        btn_onceki_sayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_onceki_sayfaActionPerformed(evt);
            }
        });

        jPanel3.setOpaque(false);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setText("ID :");

        btn_id_bul.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_id_bul.setText("BUL");
        btn_id_bul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_id_bulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_id_bul, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addGap(21, 21, 21)
                .addComponent(btn_id_bul)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txt_id_bul, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_id_bul))
                .addContainerGap())
        );

        btn_oturumu_kapat.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_oturumu_kapat.setText("OTURUMU KAPAT");
        btn_oturumu_kapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oturumu_kapatActionPerformed(evt);
            }
        });

        jPanel2.setOpaque(false);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setText("ID :");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("AD SOYAD:");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("DOĞUM TARİHİ:");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("DOĞUM YERİ:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("E-POSTA:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("TEL:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("ŞİFRE:");

        btn_silme.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_silme.setText("SİL");
        btn_silme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silmeActionPerformed(evt);
            }
        });

        btn_guncelle.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_guncelle.setText("GÜNCELLE");
        btn_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guncelleActionPerformed(evt);
            }
        });

        btn_kayit.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_kayit.setText("KAYIT");
        btn_kayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayitActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel20.setText("SEKRETER KAYIT VE  GÜNCELLEME İŞLEMİ ");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("ADRES:");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setText("CİNSİYET:");

        btn_resetle.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_resetle.setText("RESETLE");
        btn_resetle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetleActionPerformed(evt);
            }
        });

        sifregoster.setText("ŞİFREYİ GÖSTER");
        sifregoster.setOpaque(false);
        sifregoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifregosterActionPerformed(evt);
            }
        });

        cmb_cinsiye.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEÇİNİZ" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel26)
                            .addComponent(jLabel33))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(s_tel, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                .addComponent(s_id, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                            .addComponent(s_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sifregoster)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel27))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(s_dt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(s_adsoyad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btn_kayit, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btn_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel25))
                            .addComponent(s_adres, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(s_dy, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(jLabel31))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_resetle, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btn_silme)
                        .addGap(18, 18, 18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmb_cinsiye, 0, 108, Short.MAX_VALUE)
                    .addComponent(s_eposta, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(173, 173, 173))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel20)
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel22)
                    .addComponent(s_adsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(s_eposta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_id, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(s_adres, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_dy, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_dt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel28)
                    .addComponent(jLabel31)
                    .addComponent(jLabel27)
                    .addComponent(cmb_cinsiye, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(sifregoster)
                    .addComponent(s_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_kayit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_resetle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_silme, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btn_onceki_sayfa)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                        .addComponent(btn_oturumu_kapat))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_onceki_sayfa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_oturumu_kapat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(240, 40, 898, 610);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ıcon/Medical+Banner.jpg"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(0, 0, 1500, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_onceki_sayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_onceki_sayfaActionPerformed
        this.dispose();
        yonetici_islem_secme y = new yonetici_islem_secme();
        y.setVisible(true);
    }//GEN-LAST:event_btn_onceki_sayfaActionPerformed

    private void btn_kayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayitActionPerformed

        if (s_id.getText().length() == 0
                || s_adsoyad.getText().length() == 0
                || s_eposta.getText().length() == 0
                || s_tel.getText().length() == 0
                || s_sifre.getText().length() == 0
                || s_adres.getText().length() == 0
                || s_dt.getText().length() == 0
                || s_dy.getText().length() == 0) {

            helper.bosluk("fill");

        } else {
            try {
                conn = db.connection_db();
                String sql = "insert into SEKRETERKULLANİCİ "
                        + "values(?,?,?,?,?,?,?,?,?)";
                pst = conn.prepareStatement(sql);
                pst.setString(1, s_id.getText());
                 try {
                int a;
                a = Integer.parseInt(s_id.getText());
                s_id.setText("");

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "LÜTFEN ID KISMINA 11 HANELİ RAKAM GİRİNİZ!");
                s_id.setText(null);
                s_id.setFocusable(true);
            }
                pst.setString(2, s_adsoyad.getText());
                pst.setString(3, s_eposta.getText());
                pst.setString(4, s_tel.getText());
                 try {
                int i;
                i = Integer.parseInt(s_tel.getText());
                s_tel.setText("");

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "LÜTFEN TELEFON KISMINA 11 HANELİ RAKAM GİRİNİZ!");
                s_tel.setText(null);
                s_tel.setFocusable(true);
            }
                pst.setString(5, s_sifre.getText());
                pst.setString(6, s_adres.getText());
                pst.setString(7, s_dt.getText());
                pst.setString(8, s_dy.getText());
                pst.setString(9, cinsiyet);
                pst.executeUpdate();
                retrievetableSEKRETER2();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } finally {
                try {
                    JOptionPane.showMessageDialog(null, "KAYIT BAŞARILI.");
                    pst.close();
                    rs.close();
                    conn.close();
                    resetle();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);

                }
            }
        }
    }//GEN-LAST:event_btn_kayitActionPerformed

    
    private void btn_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guncelleActionPerformed
    
        try {
            conn = db.connection_db();
            String ID = s_id.getText();
            String ad_soyad = s_adsoyad.getText();
            String eposta = s_eposta.getText();
            String tel = s_tel.getText();
            String sifre = s_sifre.getText();
            String adres = s_adres.getText();
            String s_dogumt = s_dt.getText();
            String s_dogumy = s_dy.getText();
            String cinsiyet = (String) cmb_cinsiye.getSelectedItem();


            String sql = "UPDATE SEKRETERKULLANİCİ SET  ADSOYAD='" + ad_soyad + "',EPOSTA='" + eposta + "',"
                    + "TELEFON='" + tel + "',SIFRE='" + sifre + "',ADRES='" + adres + "',"
                    + "DOGUMTARIH='" + s_dogumt + "',DOGUMYERI='" + s_dogumy + "',"
                    + "CINSIYET=? WHERE SEKRETERID='" + ID + "'";
            pst = conn.prepareStatement(sql);
            pst.execute();
            retrievetableSEKRETER2();
            JOptionPane.showMessageDialog(null, "KAYIT GÜNCELLENMİŞTİR.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        } finally {
            try {

                conn.close();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e);

            }
 }

    }//GEN-LAST:event_btn_guncelleActionPerformed

    private void btn_silmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silmeActionPerformed
        if (!(s_id.getText()).equals("")) {
            try {
                conn = db.connection_db();
                String sql = "DELETE FROM SEKRETERKULLANİCİ WHERE SEKRETERID=?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, s_id.getText());
                pst.execute();
                retrievetableSEKRETER2();
                resetle();
                JOptionPane.showMessageDialog(null, "Kayıt Silinmiştir !");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } finally {
                try {

                    conn.close();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "SİLMEK İSTEDİĞİNİZ KAYDI SEÇİNİZ !");
        }
    }//GEN-LAST:event_btn_silmeActionPerformed

    private void btn_id_bulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_id_bulActionPerformed

        String SEKRETERID = "";
        String data = "";
        try {
            conn = Helper.db.connection_db();
            String sql = "SELECT * FROM SEKRETERKULLANİCİ WHERE SEKRETERID=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_id_bul.getText());
            rs = pst.executeQuery();

            if (rs.next()) {
                SEKRETERID = rs.getString("SEKRETERID");
                JOptionPane.showMessageDialog(null, "ID BULUNDU.");

            } else {
                JOptionPane.showMessageDialog(null, "ID BULUNAMADI !");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        try {
            conn.close();
            retrievetableSEKRETER(SEKRETERID);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        try {
            conn = Helper.db.connection_db();
            String sql = "SELECT * FROM SEKRETERKULLANİCİ WHERE SEKRETERID=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_id_bul.getText());
            rs = pst.executeQuery();
            while (rs.next()) {
                data = rs.getString("SEKRETERID");
                s_id.setText(data);
                data = rs.getString("ADSOYAD");
                s_adsoyad.setText(data);
                data = rs.getString("EPOSTA");
                s_eposta.setText(data);
                data = rs.getString("TELEFON");
                s_tel.setText(data);
                data = rs.getString("SIFRE");
                s_sifre.setText(data);
                data = rs.getString("ADRES");
                s_adres.setText(data);
                data = rs.getString("DOGUMTARIH");
                s_dt.setText(data);
                data = rs.getString("DOGUMYERİ");
                s_dy.setText(data);
                 data = rs.getString("CİNSİYET");
                cmb_cinsiye.setSelectedItem(data);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btn_id_bulActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        s_id.setText(model.getValueAt(i, 0).toString());
        s_adsoyad.setText(model.getValueAt(i, 1).toString());
        s_eposta.setText(model.getValueAt(i, 2).toString());
        s_tel.setText(model.getValueAt(i, 3).toString());
        s_sifre.setText(model.getValueAt(i, 4).toString());
        s_adres.setText(model.getValueAt(i, 5).toString());
        s_dt.setText(model.getValueAt(i, 6).toString());
        s_dy.setText(model.getValueAt(i, 7).toString());
        cmb_cinsiye.setSelectedItem(model.getValueAt(i, 8));
        
        

    
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_oturumu_kapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oturumu_kapatActionPerformed
        this.dispose();
        login s = new login();
        s.setVisible(true);
    }//GEN-LAST:event_btn_oturumu_kapatActionPerformed

    public void resetle() {
        txt_id_bul.setText("");
        s_id.setText("");
        s_adsoyad.setText("");
        s_eposta.setText("");
        s_tel.setText("");
        s_sifre.setText("");
        s_adres.setText("");
        s_dt.setText("");
        s_dy.setText("");
        cmb_cinsiye.setSelectedItem(null);
    }

    private void btn_resetleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetleActionPerformed
        resetle();
        retrievetableSEKRETER2();
    }//GEN-LAST:event_btn_resetleActionPerformed

    private void sifregosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifregosterActionPerformed
        if (evt.getSource() == sifregoster) {
            if (sifregoster.isSelected()) {
                s_sifre.setEchoChar((char) 0);
            } else {
                s_sifre.setEchoChar('*');
            }
        }
    }//GEN-LAST:event_sifregosterActionPerformed

    
    private void cinsiye_doldur(javax.swing.JComboBox<String> cmb_cinsiye, String sql2) {
        try {
            conn = db.connection_db();
            String sql = "SELECT * FROM CİNSİYET";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                cmb_cinsiye.addItem(rs.getString("Cinsiyet"));
            }
        } catch (Exception ex) {

        } finally {
            try {
                conn.close();
            } catch (Exception ex) {

            }
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yonetici_islem_sekreter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yonetici_islem_sekreter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yonetici_islem_sekreter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yonetici_islem_sekreter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yonetici_islem_sekreter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guncelle;
    private javax.swing.JButton btn_id_bul;
    private javax.swing.JButton btn_kayit;
    private javax.swing.JButton btn_onceki_sayfa;
    private javax.swing.JButton btn_oturumu_kapat;
    private javax.swing.JButton btn_resetle;
    private javax.swing.JButton btn_silme;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmb_cinsiye;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField s_adres;
    private javax.swing.JTextField s_adsoyad;
    private javax.swing.JTextField s_dt;
    private javax.swing.JTextField s_dy;
    private javax.swing.JTextField s_eposta;
    private javax.swing.JTextField s_id;
    private javax.swing.JPasswordField s_sifre;
    private javax.swing.JTextField s_tel;
    private javax.swing.JCheckBox sifregoster;
    private javax.swing.JTextField txt_id_bul;
    // End of variables declaration//GEN-END:variables
private String cinsiyet;
}
