/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hastatakipsist;

import Helper.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aleyna
 */
public class yonetici_islem_doktor extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int columnsNumber = 0;

    public yonetici_islem_doktor() {
        initComponents();
        retrievetableDOKTOR2();
        setSize(1500,700);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        try {
            conn = db.connection_db();
            String sql = "SELECT * FROM CİNSİYET";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                cmb_cinsiye.addItem(rs.getString("Cinsiyet"));
            }
        } catch (Exception ex) {

        } finally {
            try {
                conn.close();
            } catch (Exception ex) {

            }
        }

        try {
            conn = db.connection_db();
            String sql = "SELECT * FROM BOLUM";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                cmb_bolum.addItem(rs.getString("Bolum"));
            }
        } catch (Exception ex) {

        } finally {
            try {
                conn.close();
            } catch (Exception ex) {

            }
        }
    }

    private void retrievetableDOKTOR(String DOKTORID) {
        try {
            DefaultTableModel tbl = (DefaultTableModel) jTable1.getModel();
            while (tbl.getRowCount() > 0) {
                tbl.removeRow(0);
            }

            conn = Helper.db.connection_db();
            String sql = "SELECT * FROM DRKULLANİCİ WHERE DOKTORID='" + DOKTORID + "'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            columnsNumber = rsmd.getColumnCount();

            String[] data = new String[columnsNumber];
            while (rs.next()) {
                for (int i = 0; i < data.length; i++) {
                    data[i] = rs.getString(i + 1);
                }

                DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
                tblModel.addRow(data);
            }
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, ex);

        } finally {
            try {
                conn.close();
            } catch (Exception ex) {

                JOptionPane.showMessageDialog(null, ex);

            }
        }

    }

    private void retrievetableDOKTOR2() {
        try {
            DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
            while (table.getRowCount() > 0) {
                table.removeRow(0);
            }
            conn = db.connection_db();
            String sql = "select * from DRKULLANİCİ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            columnsNumber = rsmd.getColumnCount();

            String[] data = new String[columnsNumber];
            while (rs.next()) {
                for (int i = 0; i < data.length; i++) {
                    data[i] = rs.getString(i + 1);
                }

                DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                tableModel.addRow(data);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                conn.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_onceki_sayfa = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        txt_id_bul = new javax.swing.JTextField();
        btn_id_bul = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        d_dt = new javax.swing.JTextField();
        d_id = new javax.swing.JTextField();
        d_dy = new javax.swing.JTextField();
        d_eposta = new javax.swing.JTextField();
        d_adsoyad = new javax.swing.JTextField();
        d_tel = new javax.swing.JTextField();
        btn_silme = new javax.swing.JButton();
        btn_guncelle = new javax.swing.JButton();
        btn_kayit = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        d_adres = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        d_sifre = new javax.swing.JPasswordField();
        btn_resetle = new javax.swing.JButton();
        sifregoster = new javax.swing.JCheckBox();
        cmb_bolum = new javax.swing.JComboBox<>();
        cmb_cinsiye = new javax.swing.JComboBox<>();
        btn_oturumu_kapat = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setOpaque(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "AD SOYAD", "BOLUM", "E-POSTA", "TEL", "SIFRE", "ADRES", "DOGUM TARİHİ", "DOGUM YERİ", "CİNSİYET"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btn_onceki_sayfa.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_onceki_sayfa.setText("Önceki sayfa");
        btn_onceki_sayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_onceki_sayfaActionPerformed(evt);
            }
        });

        jPanel3.setOpaque(false);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setText("ID :");

        btn_id_bul.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_id_bul.setText("BUL");
        btn_id_bul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_id_bulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addComponent(txt_id_bul, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btn_id_bul)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txt_id_bul, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_id_bul))
                .addContainerGap())
        );

        jPanel2.setOpaque(false);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setText("ID :");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("AD SOYAD  :");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("BÖLÜM  :");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("DOĞUM TARİHİ  :");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("DOĞUM YERİ  :");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("E-POSTA  :");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("TELEFON  :");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("ŞİFRE:");

        d_adsoyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_adsoyadActionPerformed(evt);
            }
        });

        d_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_telActionPerformed(evt);
            }
        });

        btn_silme.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_silme.setText("SİL");
        btn_silme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silmeActionPerformed(evt);
            }
        });

        btn_guncelle.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_guncelle.setText("GÜNCELLE");
        btn_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guncelleActionPerformed(evt);
            }
        });

        btn_kayit.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_kayit.setText("KAYIT");
        btn_kayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayitActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel20.setText("DOKTOR KAYIT VE  GÜNCELLEME İŞLEMİ ");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("ADRES  :");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setText("CİNSİYET  :");

        btn_resetle.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_resetle.setText("RESETLE");
        btn_resetle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetleActionPerformed(evt);
            }
        });

        sifregoster.setText("ŞİFREYİ GÖSTER");
        sifregoster.setOpaque(false);
        sifregoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifregosterActionPerformed(evt);
            }
        });

        cmb_bolum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEÇİNİZ" }));

        cmb_cinsiye.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEÇİNİZ" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_kayit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(10, 10, 10)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmb_cinsiye, 0, 122, Short.MAX_VALUE)
                            .addComponent(d_tel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(d_id, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22)
                                .addGap(12, 12, 12))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btn_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                            .addComponent(btn_resetle, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(d_adsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel24))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(d_dt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel28)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(d_dy)
                                .addComponent(cmb_bolum, 0, 108, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(d_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sifregoster)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_silme, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(d_adres, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d_eposta, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(173, 173, 173))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel20)
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel22)
                    .addComponent(jLabel24)
                    .addComponent(d_adsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(d_id, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_eposta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_bolum, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(d_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(d_dy, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(d_dt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26)
                        .addComponent(jLabel27)
                        .addComponent(jLabel28)
                        .addComponent(jLabel30)
                        .addComponent(d_adres, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(d_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sifregoster))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmb_cinsiye, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel31)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_silme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_kayit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_resetle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        btn_oturumu_kapat.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        btn_oturumu_kapat.setText("OTURUMU KAPAT");
        btn_oturumu_kapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oturumu_kapatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btn_onceki_sayfa)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_oturumu_kapat))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_onceki_sayfa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn_oturumu_kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(240, 50, 910, 610);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ıcon/Medical+Banner.jpg"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(0, 0, 1500, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayitActionPerformed

        if (d_id.getText().length() == 0
                || d_adsoyad.getText().length() == 0
                || cmb_bolum.getSelectedIndex() == 0
                || d_eposta.getText().length() == 0
                || d_tel.getText().length() == 0
                || d_sifre.getText().length() == 0
                || d_adres.getText().length() == 0
                || d_dt.getText().length() == 0
                || d_dy.getText().length() == 0
                || cmb_cinsiye.getSelectedIndex() == 0) {

            helper.bosluk("fill");

        } else {
            try {
                conn = db.connection_db();
                String sql = "insert into DRKULLANİCİ "
                        + "values(?,?,?,?,?,?,?,?,?,?)";
                pst = conn.prepareStatement(sql);
                pst.setString(1, d_id.getText());
                pst.setString(2, d_adsoyad.getText());
                pst.setString(3, (String) cmb_bolum.getSelectedItem());
                pst.setString(4, d_eposta.getText());
                pst.setString(5, d_tel.getText());
                pst.setString(6, d_sifre.getText());
                pst.setString(7, d_adres.getText());
                pst.setString(8, d_dt.getText());
                pst.setString(11, d_dy.getText());
                pst.setString(12, (String) cmb_cinsiye.getSelectedItem());
                pst.execute();
                retrievetableDOKTOR2();
                JOptionPane.showMessageDialog(null, "KAYIT BAŞARILI.");

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e);

            } finally {
                try {
                    resetle();
                    rs.close();
                    pst.close();
                    conn.close();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);

                }
            }
        }

    }//GEN-LAST:event_btn_kayitActionPerformed

    private void btn_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guncelleActionPerformed

        try {
           conn = db.connection_db();
            String ID = d_id.getText();
            String ad_soyad = d_adsoyad.getText();
            String bolum = (String)cmb_bolum.getSelectedItem();
            String eposta = d_eposta.getText();
            String tel = d_tel.getText();
            String sifre = d_sifre.getText();
            String adres = d_adres.getText();
            String d_dogumt = d_dt.getText();
            String d_dogumy = d_dy.getText();
            String cinsiye = (String)cmb_cinsiye.getSelectedItem();

            String sql = "UPDATE DRKULLANİCİ SET  ADSOYAD='" + ad_soyad + "',BOLUM='" + bolum + "',"
                    + "EPOSTA='" + eposta + "',TELEFON='" + tel + "',SIFRE='" + sifre + "',"
                    + "ADRES='" + adres + "',DOGUMTARIH='" + d_dogumt + "',DOGUMYERİ='" + d_dogumy + "' WHERE DOKTORID='" + ID + "'";
            pst = conn.prepareStatement(sql);
            pst.execute();
            retrievetableDOKTOR2();
            JOptionPane.showMessageDialog(null, "KAYIT GÜNCELLENMİŞTİR.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        } finally {
            try {

                conn.close();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e);

            }

        }

    }//GEN-LAST:event_btn_guncelleActionPerformed

    private void btn_silmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silmeActionPerformed
        if (!(d_id.getText()).equals("")) {
            try {
                conn = db.connection_db();
                String sql = "DELETE FROM DRKULLANİCİ WHERE DOKTORID=?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, d_id.getText());
                pst.execute();
                retrievetableDOKTOR2();
                resetle();
                JOptionPane.showMessageDialog(null, "Kayıt Silinmiştir !");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            } finally {
                try {

                    conn.close();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "SİLMEK İSTEDİĞİNİZ KAYDI SEÇİNİZ !");
        }
    }//GEN-LAST:event_btn_silmeActionPerformed

    private void btn_id_bulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_id_bulActionPerformed
        String DOKTORID = "";
        String data = "";
        try {
            conn = Helper.db.connection_db();
            String sql = "SELECT * FROM DRKULLANİCİ WHERE DOKTORID=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_id_bul.getText());
            rs = pst.executeQuery();

            if (rs.next()) {
                DOKTORID = rs.getString("DOKTORID");
                JOptionPane.showMessageDialog(null, "ID bulundu");

            } else {
                JOptionPane.showMessageDialog(null, "Böyle bir ID yoktur");
            }
        } catch (Exception ex) {

        }
        try {
            conn.close();
            retrievetableDOKTOR(DOKTORID);

        } catch (Exception ex) {

        }

        try {
            conn = Helper.db.connection_db();
            String sql = "SELECT * FROM DRKULLANİCİ WHERE DOKTORID=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_id_bul.getText());
            rs = pst.executeQuery();
            while (rs.next()) {
                data = rs.getString("DOKTORID");
                d_id.setText(data);
                data = rs.getString("ADSOYAD");
                d_adsoyad.setText(data);
                data = rs.getString("BOLUM");
                cmb_bolum.setSelectedItem(data);
                data = rs.getString("EPOSTA");
                d_eposta.setText(data);
                data = rs.getString("TELEFON");
                d_tel.setText(data);
                data = rs.getString("SIFRE");
                d_sifre.setText(data);
                data = rs.getString("ADRES");
                d_adres.setText(data);
                data = rs.getString("DOGUMTARIH");
                d_dt.setText(data);
                data = rs.getString("DOGUMYERİ");
                d_dy.setText(data);
                data = rs.getString("CINSIYET");
                cmb_cinsiye.setSelectedItem(data);

            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_btn_id_bulActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        String[] data = new String[columnsNumber];
        for (int i = 0; i < data.length; i++) {
            data[i] = jTable1.getValueAt(jTable1.getSelectedRow(), i).toString();
        }
        d_id.setText(data[0]);
        d_adsoyad.setText(data[1]);
        cmb_bolum.setSelectedItem(data[2]);
        d_eposta.setText(data[3]);
        d_tel.setText(data[4]);
        d_sifre.setText(data[5]);
        d_adres.setText(data[6]);
        d_dt.setText(data[7]);
        d_dy.setText(data[8]);
        cmb_cinsiye.setSelectedItem(data[9]);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_onceki_sayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_onceki_sayfaActionPerformed
        this.dispose();
        yonetici_islem_secme y = new yonetici_islem_secme();
        y.setVisible(true);
    }//GEN-LAST:event_btn_onceki_sayfaActionPerformed

    private void resetle() {

        txt_id_bul.setText("");
        d_id.setText("");
        d_adsoyad.setText("");
        cmb_bolum.setSelectedItem(null);
        d_eposta.setText("");
        d_tel.setText("");
        d_sifre.setText("");
        d_adres.setText("");
        d_dt.setText("");
        d_dy.setText("");
        cmb_cinsiye.setSelectedItem(null);

    }

    private void btn_resetleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetleActionPerformed
        resetle();
        retrievetableDOKTOR2();
    }//GEN-LAST:event_btn_resetleActionPerformed

    private void sifregosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifregosterActionPerformed
        if (evt.getSource() == sifregoster) {
            if (sifregoster.isSelected()) {
                d_sifre.setEchoChar((char) 0);
            } else {
                d_sifre.setEchoChar('*');
            }
        }
    }//GEN-LAST:event_sifregosterActionPerformed

    private void btn_oturumu_kapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oturumu_kapatActionPerformed
        this.dispose();
        login l = new login();
        l.setVisible(true);
    }//GEN-LAST:event_btn_oturumu_kapatActionPerformed

    private void d_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d_telActionPerformed

    private void d_adsoyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_adsoyadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d_adsoyadActionPerformed

    private void cinsiye_doldur(javax.swing.JComboBox<String> cmb_cinsiye, String sql2) {
        try {
            conn = db.connection_db();
            String sql = "SELECT * FROM CİNSİYET";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                cmb_cinsiye.addItem(rs.getString("Cinsiyet"));
            }
        } catch (Exception ex) {

        } finally {
            try {
                conn.close();
            } catch (Exception ex) {

            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yonetici_islem_doktor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yonetici_islem_doktor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yonetici_islem_doktor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yonetici_islem_doktor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yonetici_islem_doktor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guncelle;
    private javax.swing.JButton btn_id_bul;
    private javax.swing.JButton btn_kayit;
    private javax.swing.JButton btn_onceki_sayfa;
    private javax.swing.JButton btn_oturumu_kapat;
    private javax.swing.JButton btn_resetle;
    private javax.swing.JButton btn_silme;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmb_bolum;
    private javax.swing.JComboBox<String> cmb_cinsiye;
    private javax.swing.JTextField d_adres;
    private javax.swing.JTextField d_adsoyad;
    private javax.swing.JTextField d_dt;
    private javax.swing.JTextField d_dy;
    private javax.swing.JTextField d_eposta;
    private javax.swing.JTextField d_id;
    private javax.swing.JPasswordField d_sifre;
    private javax.swing.JTextField d_tel;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JCheckBox sifregoster;
    private javax.swing.JTextField txt_id_bul;
    // End of variables declaration//GEN-END:variables
private String cinsiyet;
}
